apiVersion: v1
kind: Service
metadata:
  name: selenium-chrome-node
  labels:
spec:
  type: ClusterIP
  selector:
    app: selenium-chrome-node
  ports:
    - name: tcp-chrome
      protocol: TCP
      port: 6900
      targetPort: 5900